name: Git page deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install python2
        run: apt update && DEBIAN_FRONTEND=noninteractive apt install -y python2 make g++
      - name: Test python2
        run: python2 --version
      - run: npm install sass node-sass@4.14.1

      - name: Install and build
        run: npm install && npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
